#!/bin/bash

export CUDA_VISIBLE_DEVICES=$1
p=$2

DATA_PATH=/scratch/aewood/ogb_graphs/synthetic
GIT_PATH=/scratch/aewood/git/ogb/examples/linkproppred/random
MODEL_PATH=${DATA_PATH}/models/base/RotatE/p-$p


_CD_=$pwd

cd $DATA_PATH

python ${GIT_PATH}/run.py --dataset ogbl-base-p-${p} --model RotatE --print_on_screen --do_train --cuda --save_path ${MODEL_PATH} --save_checkpoint_steps 1000 --double_entity_embedding

cd $_CD_

