#!/bin/bash

# turn output file with entries n n [ ... ] into single lines

sed 's/\] \[//' $* | tr -d '[' | sed 's/\]/\
/' | awk '/# score|brks|---/ {next} /^$/ { print data; data = ""; next } { data = data " " $0 }'
