#!/bin/bash
# look at train.log or test.log and extract final results.

for dir
do
	for FILE in $dir/train.log $dir/test.log
	do  if [ -r $FILE ]
	    then
		OUT=$dir/summary.txt
	    	head -100 $FILE | sed -n '1,/Train loss at step 0:/s/.*INFO *//p' >$OUT
		tail -100 $FILE | grep -v illegal | sed -n '/Evaluating on Test Dataset/,$/s/.*INFO *//p' >$OUT
	    fi
	done
done
