#!/bin/bash

# GIT_ROOT=/scratch/aewood/git/ogb/examples/linkproppred/random
# DATA_ROOT=/scratch/aewood/ogb_graphs/synthetic

GIT_ROOT=~/git/bu/research/ogb/examples/linkproppred/random
DATA_ROOT=/scratch/ogb/synthetic

_CD_ = $pwd

cd $DATA_ROOT

#### 10k vertex graphs
echo ""
echo ""
echo "################################"
echo "10k graphs"
echo "################################"
echo ""
echo ""

# make random-graph1
python $GIT_ROOT/convertkg.py ogbl-rand1 --mode read_triples --file $DATA_ROOT/random_graph_1.csv --noise_first_row 7497

# make random-graph2
python $GIT_ROOT/convertkg.py ogbl-rand2 --mode read_triples --file $DATA_ROOT/random_graph_2.csv --noise_first_row 7497

# make random-graph3
python $GIT_ROOT/convertkg.py ogbl-rand3 --mode read_triples --file $DATA_ROOT/random_graph_3.csv --noise_first_row 7497

# make random-graph4
python $GIT_ROOT/convertkg.py ogbl-rand4 --mode read_triples --file $DATA_ROOT/random_graph_4.csv --noise_first_row 4494


#### 100k vertex graphs
echo ""
echo ""
echo "################################"
echo "100k graphs"
echo "################################"
echo ""
echo ""


python $GIT_ROOT/convertkg.py ogbl-100k-rand1 --mode read_triples --file $DATA_ROOT/RG1_10.csv --noise_first_row 749991

python $GIT_ROOT/convertkg.py ogbl-100k-rand2 --mode read_triples --file $DATA_ROOT/RG2_10.csv --noise_first_row 749991

python $GIT_ROOT/convertkg.py ogbl-100k-rand3 --mode read_triples --file $DATA_ROOT/RG3_10.csv --noise_first_row 749991

python $GIT_ROOT/convertkg.py ogbl-100k-rand4 --mode read_triples --file $DATA_ROOT/RG4_10.csv --noise_first_row 449994


#### 50k graph
echo ""
echo ""
echo "################################"
echo "50k graphs"
echo "################################"
echo ""
echo ""

python $GIT_ROOT/convertkg.py ogbl-50k-test --mode read_triples --file $DATA_ROOT/50k_test.csv


#### base* graphs
echo ""
echo ""
echo "################################"
echo "base graphs"
echo "################################"
echo ""
echo ""

python $GIT_ROOT/convertkg.py ogbl-base-p--1 --mode read_triples --file $DATA_ROOT/base.csv --noise_first_row 9999

python $GIT_ROOT/convertkg.py ogbl-base-p-0.4 --mode read_triples --file $DATA_ROOT/base_with_p_0.4_over_n.csv --noise_first_row 9999

python $GIT_ROOT/convertkg.py ogbl-base-p-0.5 --mode read_triples --file $DATA_ROOT/base_with_p_0.5_over_n.csv --noise_first_row 9999

python $GIT_ROOT/convertkg.py ogbl-base-p-0.6 --mode read_triples --file $DATA_ROOT/base_with_p_0.6000000000000001_over_n.csv --noise_first_row 9999

python $GIT_ROOT/convertkg.py ogbl-base-p-0.7 --mode read_triples --file $DATA_ROOT/base_with_p_0.7000000000000001_over_n.csv --noise_first_row 9999

python $GIT_ROOT/convertkg.py ogbl-base-p-0.8 --mode read_triples --file $DATA_ROOT/base_with_p_0.8_over_n.csv --noise_first_row 9999

python $GIT_ROOT/convertkg.py ogbl-base-p-0.9 --mode read_triples --file $DATA_ROOT/base_with_p_0.9_over_n.csv --noise_first_row 9999

python $GIT_ROOT/convertkg.py ogbl-base-p-1.0 --mode read_triples --file $DATA_ROOT/base_with_p_1.0_over_n.csv --noise_first_row 9999

cd $_CD_

