#!/bin/bash
# go through a set of runs and redo the tests

RETEST=$1 ; shift
RETEST_OPTIONS="--test_random_sample 500 --ntriples_eval_train 5000"

cuda=1
maxcuda=7

for i
do  if [[ -r $i/checkpoint ]] && [[ -r $i/summary.txt ]]
    then if [[ -r $i/retest.$RETEST ]] ; then :
    	 else
	     CUDA_VISIBLE_DEVICES=$cuda \
		nohup python run.py --cuda --do_test $RETEST_OPTIONS \
		--init $i --evaluator $RETEST >$i/retest.$RETEST.new || exit 1
	     awk '!on && /score/ {on=1;print} on && !/score/ {print}' $i/retest.$RETEST.new >$i/retest.$RETEST
	     mv 
#	     cuda=$((cuda+1))
#	     [[ $cuda > $maxcuda ]] && exit 0
	 fi
    fi
done
